version: '3.8'

services:
  db:
    image: postgres:15
    container_name: emt-postgres
    restart: always
    environment:
      POSTGRES_DB: emt
      POSTGRES_USER: emt
      POSTGRES_PASSWORD: emt
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
